import { ProgramConfig, ProgramId } from '../../src/types.ts';

export const UFAZ_PROGRAMS: Record<ProgramId, ProgramConfig> = {
  cs: {
    id: 'cs',
    name: 'Computer Science',
    frenchName: 'Informatique',
    partnerUniversity: 'Université de Strasbourg (Unistra)',
    level: 'L2',
    semester: 'Semester 4',
    totalEcts: 30,
    totalGpaWeight: 30,
    gpaFormulaText: 'GPA = (Vector Analysis × 5 + Physics_3 × 7 + French × 3 + Computer Science × 15) / 30',
    modules: [
      {
        id: 'cs_va',
        name: 'Vector Analysis',
        code: 'MATH-201',
        ects: 5,
        gpaWeight: 5,
        formulaDescription: 'Vector Analysis = (Notebook × 2 + Vector Analysis Midterm × 3 + Vector Analysis Final × 5) / 10',
        components: [
          { id: 'cs_va_nb', name: 'Notebook', label: 'Notebook', weight: 2, maxScore: 20, description: 'Continuous coursework notebook & exercises' },
          { id: 'cs_va_mid', name: 'Midterm', label: 'Vector Analysis Midterm', weight: 3, maxScore: 20, description: 'Mid-term written examination' },
          { id: 'cs_va_fin', name: 'Final', label: 'Vector Analysis Final', weight: 5, maxScore: 20, description: 'Final comprehensive exam' },
        ],
      },
      {
        id: 'cs_phy3',
        name: 'Physics_3',
        code: 'PHYS-203',
        ects: 7,
        gpaWeight: 7,
        formulaDescription: 'Physics_3 = (Electricity × 2 + ((Electromagnetism Midterm + Electromagnetism Final) × 3 / 2)) / 5',
        components: [
          { id: 'cs_phy3_elec', name: 'Electricity', label: 'Electricity', weight: 2, maxScore: 20, description: 'Electricity lab / continuous evaluation' },
          { id: 'cs_phy3_em_mid', name: 'EM Midterm', label: 'Electromagnetism Midterm', weight: 1.5, maxScore: 20, description: 'Midterm assessment' },
          { id: 'cs_phy3_em_fin', name: 'EM Final', label: 'Electromagnetism Final', weight: 1.5, maxScore: 20, description: 'Final assessment' },
        ],
      },
      {
        id: 'cs_fr',
        name: 'French',
        code: 'LANG-201',
        ects: 3,
        gpaWeight: 3,
        formulaDescription: 'French = (French Midterm × 2 + French Speaking × 3 + French Final × 3) / 8',
        components: [
          { id: 'cs_fr_mid', name: 'French Midterm', label: 'French Midterm', weight: 2, maxScore: 20, description: 'Written grammar & comprehension' },
          { id: 'cs_fr_spk', name: 'French Speaking', label: 'French Speaking', weight: 3, maxScore: 20, description: 'Oral production & interview' },
          { id: 'cs_fr_fin', name: 'French Final', label: 'French Final', weight: 3, maxScore: 20, description: 'Final comprehensive examination' },
        ],
      },
      {
        id: 'cs_cs_mod',
        name: 'Computer Science',
        code: 'INFO-200',
        ects: 15,
        gpaWeight: 15,
        formulaDescription: 'Computer Science = ((Software Eng. + Signal Proc. + Systems Prog. + IP Networks + Back-End) / 5)',
        subGroups: [
          {
            id: 'se',
            name: 'Software Engineering',
            formulaText: '(Software Engineering PW + Software Engineering Final) / 2',
            components: [
              { id: 'cs_se_pw', name: 'PW', label: 'Software Eng. PW', maxScore: 20 },
              { id: 'cs_se_fin', name: 'Final', label: 'Software Eng. Final', maxScore: 20 },
            ],
          },
          {
            id: 'sp',
            name: 'Signal Processing',
            formulaText: '(Signal Processing PW × 2 + Signal Processing Final × 3) / 5',
            components: [
              { id: 'cs_sp_pw', name: 'PW', label: 'Signal Processing PW', maxScore: 20 },
              { id: 'cs_sp_fin', name: 'Final', label: 'Signal Processing Final', maxScore: 20 },
            ],
          },
          {
            id: 'sys',
            name: 'Systems Programming',
            formulaText: '(Systems Programming PW + Systems Programming Final) / 2',
            components: [
              { id: 'cs_sys_pw', name: 'PW', label: 'Systems Prog. PW', maxScore: 20 },
              { id: 'cs_sys_fin', name: 'Final', label: 'Systems Prog. Final', maxScore: 20 },
            ],
          },
          {
            id: 'net',
            name: 'IP Networks',
            formulaText: '(IP Networks Midterm + IP Networks Final) / 2',
            components: [
              { id: 'cs_net_mid', name: 'Midterm', label: 'IP Networks Midterm', maxScore: 20 },
              { id: 'cs_net_fin', name: 'Final', label: 'IP Networks Final', maxScore: 20 },
            ],
          },
          {
            id: 'be',
            name: 'Back-End Development',
            formulaText: '(Back-End Participation + Back-End PW × 4 + Back-End Final × 5) / 10',
            components: [
              { id: 'cs_be_part', name: 'Participation', label: 'Back-End Participation', maxScore: 20 },
              { id: 'cs_be_pw', name: 'PW', label: 'Back-End PW', maxScore: 20 },
              { id: 'cs_be_fin', name: 'Final', label: 'Back-End Final', maxScore: 20 },
            ],
          },
        ],
        components: [],
      },
    ],
  },
  che: {
    id: 'che',
    name: 'Chemical Engineering',
    frenchName: 'Génie Chimique',
    partnerUniversity: 'Université de Strasbourg (ECPM / Unistra)',
    level: 'L2',
    semester: 'Semester 4',
    totalEcts: 30,
    totalGpaWeight: 30,
    gpaFormulaText: 'GPA = (Vector Analysis × 5 + Chemistry_3 × 9 + Chemical Engineering_3 × 8 + Physics_3 × 5 + French × 3) / 30',
    modules: [
      {
        id: 'che_va',
        name: 'Vector Analysis',
        code: 'MATH-201',
        ects: 5,
        gpaWeight: 5,
        formulaDescription: 'Vector Analysis = (Notebook × 2 + Vector Analysis Midterm × 3 + Vector Analysis Final × 5) / 10',
        components: [
          { id: 'che_va_nb', name: 'Notebook', label: 'Notebook', weight: 2, maxScore: 20 },
          { id: 'che_va_mid', name: 'Midterm', label: 'Vector Analysis Midterm', weight: 3, maxScore: 20 },
          { id: 'che_va_fin', name: 'Final', label: 'Vector Analysis Final', weight: 5, maxScore: 20 },
        ],
      },
      {
        id: 'che_chem3',
        name: 'Chemistry_3',
        code: 'CHEM-203',
        ects: 9,
        gpaWeight: 9,
        formulaDescription: 'Chemistry_3 = ((Reactivity Midterm + Reactivity Final × 2)/3 × 3 + (Thermo and Kinetics Midterm + Thermo and Kinetics Final)/2 × 2 + Chem Evaluated PW × 3) / 8',
        subGroups: [
          {
            id: 'react',
            name: 'Reactivity (Coeff 3/8)',
            formulaText: '(Reactivity Midterm + Reactivity Final × 2) / 3',
            components: [
              { id: 'che_chem3_react_mid', name: 'Midterm', label: 'Reactivity Midterm', maxScore: 20 },
              { id: 'che_chem3_react_fin', name: 'Final', label: 'Reactivity Final', maxScore: 20 },
            ],
          },
          {
            id: 'thermo',
            name: 'Thermo and Kinetics (Coeff 2/8)',
            formulaText: '(Thermo and Kinetics Midterm + Thermo and Kinetics Final) / 2',
            components: [
              { id: 'che_chem3_tk_mid', name: 'Midterm', label: 'Thermo & Kinetics Midterm', maxScore: 20 },
              { id: 'che_chem3_tk_fin', name: 'Final', label: 'Thermo & Kinetics Final', maxScore: 20 },
            ],
          },
          {
            id: 'lab',
            name: 'Chemistry Evaluated PW (Coeff 3/8)',
            formulaText: 'Chem Evaluated PW Score',
            components: [
              { id: 'che_chem3_eval_pw', name: 'PW', label: 'Chem Evaluated PW', maxScore: 20 },
            ],
          },
        ],
        components: [],
      },
      {
        id: 'che_ce3',
        name: 'Chemical Engineering_3',
        code: 'GCH-203',
        ects: 8,
        gpaWeight: 8,
        formulaDescription: 'Chemical Engineering_3 = (Distillation Final + (Operation on Solids Written Exam + Report/Behavior × 0.5 + PW Written Exam × 0.5) / 2 × 2 + Liquid-liquid Extraction) / 4',
        subGroups: [
          {
            id: 'dist',
            name: 'Distillation',
            formulaText: 'Distillation Final',
            components: [
              { id: 'che_ce3_dist_fin', name: 'Final', label: 'Distillation Final', maxScore: 20 },
            ],
          },
          {
            id: 'solids',
            name: 'Operation on Solids (Weight × 2)',
            formulaText: '(Written Exam + Report/Behavior × 0.5 + PW Written Exam × 0.5) / 2',
            components: [
              { id: 'che_ce3_solids_written', name: 'Written Exam', label: 'Operation on Solids Written Exam', maxScore: 20 },
              { id: 'che_ce3_solids_rep', name: 'Report/Behavior', label: 'Report / Behavior', maxScore: 20 },
              { id: 'che_ce3_solids_pw_exam', name: 'PW Written Exam', label: 'PW Written Exam', maxScore: 20 },
            ],
          },
          {
            id: 'lle',
            name: 'Liquid-Liquid Extraction',
            formulaText: 'Liquid-Liquid Extraction',
            components: [
              { id: 'che_ce3_lle', name: 'Extraction', label: 'Liquid-liquid Extraction', maxScore: 20 },
            ],
          },
        ],
        components: [],
      },
      {
        id: 'che_phy3',
        name: 'Physics_3',
        code: 'PHYS-203',
        ects: 5,
        gpaWeight: 5,
        formulaDescription: 'Physics_3 = (Electricity + ((Thermodynamics Midterm + Thermodynamics Final) / 2)) / 2',
        components: [
          { id: 'che_phy3_elec', name: 'Electricity', label: 'Electricity', weight: 1, maxScore: 20 },
          { id: 'che_phy3_th_mid', name: 'Thermo Midterm', label: 'Thermodynamics Midterm', weight: 0.5, maxScore: 20 },
          { id: 'che_phy3_th_fin', name: 'Thermo Final', label: 'Thermodynamics Final', weight: 0.5, maxScore: 20 },
        ],
      },
      {
        id: 'che_fr',
        name: 'French',
        code: 'LANG-201',
        ects: 3,
        gpaWeight: 3,
        formulaDescription: 'French = (French Midterm × 2 + French Speaking × 3 + French Final × 3) / 8',
        components: [
          { id: 'che_fr_mid', name: 'French Midterm', label: 'French Midterm', weight: 2, maxScore: 20 },
          { id: 'che_fr_spk', name: 'French Speaking', label: 'French Speaking', weight: 3, maxScore: 20 },
          { id: 'che_fr_fin', name: 'French Final', label: 'French Final', weight: 3, maxScore: 20 },
        ],
      },
    ],
  },
  ge: {
    id: 'ge',
    name: 'Geophysical Engineering',
    frenchName: 'Géophysique',
    partnerUniversity: 'Université de Strasbourg (EOST / Unistra)',
    level: 'L2',
    semester: 'Semester 4',
    totalEcts: 30,
    totalGpaWeight: 30,
    gpaFormulaText: 'GPA = (Vector Analysis × 5 + Physics_3 × 8 + French × 3 + Geology_1 × 14) / 30',
    modules: [
      {
        id: 'ge_va',
        name: 'Vector Analysis',
        code: 'MATH-201',
        ects: 5,
        gpaWeight: 5,
        formulaDescription: 'Vector Analysis = (Notebook × 2 + Vector Analysis Midterm × 3 + Vector Analysis Final × 5) / 10',
        components: [
          { id: 'ge_va_nb', name: 'Notebook', label: 'Notebook', weight: 2, maxScore: 20 },
          { id: 'ge_va_mid', name: 'Midterm', label: 'Vector Analysis Midterm', weight: 3, maxScore: 20 },
          { id: 'ge_va_fin', name: 'Final', label: 'Vector Analysis Final', weight: 5, maxScore: 20 },
        ],
      },
      {
        id: 'ge_phy3',
        name: 'Physics_3',
        code: 'PHYS-203',
        ects: 8,
        gpaWeight: 8,
        formulaDescription: 'Physics_3 = ((Electromagnetism Midterm + Electromagnetism Final) × 3 / 2 + (Thermodynamics Midterm + Thermodynamics Final) / 2 × 2 + Solid Mechanics × 2) / 7',
        subGroups: [
          {
            id: 'em',
            name: 'Electromagnetism (Weight 3/7)',
            formulaText: '(Electromagnetism Midterm + Electromagnetism Final) × 3 / 2',
            components: [
              { id: 'ge_phy3_em_mid', name: 'Midterm', label: 'Electromagnetism Midterm', maxScore: 20 },
              { id: 'ge_phy3_em_fin', name: 'Final', label: 'Electromagnetism Final', maxScore: 20 },
            ],
          },
          {
            id: 'th',
            name: 'Thermodynamics (Weight 2/7)',
            formulaText: '(Thermodynamics Midterm + Thermodynamics Final) / 2 × 2',
            components: [
              { id: 'ge_phy3_th_mid', name: 'Midterm', label: 'Thermodynamics Midterm', maxScore: 20 },
              { id: 'ge_phy3_th_fin', name: 'Final', label: 'Thermodynamics Final', maxScore: 20 },
            ],
          },
          {
            id: 'sm',
            name: 'Solid Mechanics (Weight 2/7)',
            formulaText: 'Solid Mechanics × 2',
            components: [
              { id: 'ge_phy3_sm', name: 'Solid Mechanics', label: 'Solid Mechanics Score', maxScore: 20 },
            ],
          },
        ],
        components: [],
      },
      {
        id: 'ge_fr',
        name: 'French',
        code: 'LANG-201',
        ects: 3,
        gpaWeight: 3,
        formulaDescription: 'French = (French Midterm × 2 + French Speaking × 3 + French Final × 3) / 8',
        components: [
          { id: 'ge_fr_mid', name: 'French Midterm', label: 'French Midterm', weight: 2, maxScore: 20 },
          { id: 'ge_fr_spk', name: 'French Speaking', label: 'French Speaking', weight: 3, maxScore: 20 },
          { id: 'ge_fr_fin', name: 'French Final', label: 'French Final', weight: 3, maxScore: 20 },
        ],
      },
      {
        id: 'ge_geo1',
        name: 'Geology_1',
        code: 'GEOL-201',
        ects: 14,
        gpaWeight: 14,
        formulaDescription: 'Geology_1 = (Sedimentology + Depositional Environments Final × 2 + (Cartography and GIS Final + Project) / 2 × 2 + Structural Geology × 2 + Basin Analysis and Stratigraphy Final × 2 + (Geochemistry(PW) + Geochemistry Final) / 2 × 2) / 11',
        components: [
          { id: 'ge_sed', name: 'Sedimentology', label: 'Sedimentology', weight: 1, maxScore: 20 },
          { id: 'ge_dep_fin', name: 'Dep. Environments Final', label: 'Depositional Environments Final', weight: 2, maxScore: 20 },
          { id: 'ge_gis_fin', name: 'Cartography & GIS Final', label: 'Cartography and GIS Final', weight: 1, maxScore: 20 },
          { id: 'ge_gis_proj', name: 'Cartography & GIS Project', label: 'Cartography and GIS Project', weight: 1, maxScore: 20 },
          { id: 'ge_struct', name: 'Structural Geology', label: 'Structural Geology', weight: 2, maxScore: 20 },
          { id: 'ge_basin_fin', name: 'Basin Analysis Final', label: 'Basin Analysis & Stratigraphy Final', weight: 2, maxScore: 20 },
          { id: 'ge_geochem_pw', name: 'Geochemistry(PW)', label: 'Geochemistry (PW)', weight: 1, maxScore: 20 },
          { id: 'ge_geochem_fin', name: 'Geochemistry Final', label: 'Geochemistry Final', weight: 1, maxScore: 20 },
        ],
      },
    ],
  },
  pe: {
    id: 'pe',
    name: 'Petroleum Engineering',
    frenchName: 'Génie Pétrolier',
    partnerUniversity: 'Université de Rennes 1 / Unistra',
    level: 'L2',
    semester: 'Semester 4',
    totalEcts: 30,
    totalGpaWeight: 30,
    gpaFormulaText: 'GPA = (Vector Analysis × 5 + Physics_3 × 5 + French × 3 + Petroleum Geology × 17) / 30',
    modules: [
      {
        id: 'pe_va',
        name: 'Vector Analysis',
        code: 'MATH-201',
        ects: 5,
        gpaWeight: 5,
        formulaDescription: 'Vector Analysis = (Notebook × 2 + Vector Analysis Midterm × 3 + Vector Analysis Final × 5) / 10',
        components: [
          { id: 'pe_va_nb', name: 'Notebook', label: 'Notebook', weight: 2, maxScore: 20 },
          { id: 'pe_va_mid', name: 'Midterm', label: 'Vector Analysis Midterm', weight: 3, maxScore: 20 },
          { id: 'pe_va_fin', name: 'Final', label: 'Vector Analysis Final', weight: 5, maxScore: 20 },
        ],
      },
      {
        id: 'pe_phy3',
        name: 'Physics_3',
        code: 'PHYS-203',
        ects: 5,
        gpaWeight: 5,
        formulaDescription: 'Physics_3 = ((Thermodynamics Midterm + Thermodynamics Final) / 2 + Solid Mechanics) / 2',
        components: [
          { id: 'pe_phy3_th_mid', name: 'Thermo Midterm', label: 'Thermodynamics Midterm', weight: 0.5, maxScore: 20 },
          { id: 'pe_phy3_th_fin', name: 'Thermo Final', label: 'Thermodynamics Final', weight: 0.5, maxScore: 20 },
          { id: 'pe_phy3_sm', name: 'Solid Mechanics', label: 'Solid Mechanics', weight: 1, maxScore: 20 },
        ],
      },
      {
        id: 'pe_fr',
        name: 'French',
        code: 'LANG-201',
        ects: 3,
        gpaWeight: 3,
        formulaDescription: 'French = (French Midterm × 2 + French Speaking × 3 + French Final × 3) / 8',
        components: [
          { id: 'pe_fr_mid', name: 'French Midterm', label: 'French Midterm', weight: 2, maxScore: 20 },
          { id: 'pe_fr_spk', name: 'French Speaking', label: 'French Speaking', weight: 3, maxScore: 20 },
          { id: 'pe_fr_fin', name: 'French Final', label: 'French Final', weight: 3, maxScore: 20 },
        ],
      },
      {
        id: 'pe_petro_geo',
        name: 'Petroleum Geology',
        code: 'GEOL-203',
        ects: 17,
        gpaWeight: 17,
        formulaDescription: 'Petroleum Geology = (Sedimentology + Depositional Environments Final × 2 + (Cartography and GIS Final + Project) / 2 × 2 + Structural Geology × 2 + Basin Analysis and Stratigraphy Final × 2 + Geology for PS Final × 2 + Reservoir Engineering × 2 + (Geochemistry(Project) + Geochemistry Final) / 2 × 2) / 15',
        components: [
          { id: 'pe_sed', name: 'Sedimentology', label: 'Sedimentology', weight: 1, maxScore: 20 },
          { id: 'pe_dep_fin', name: 'Dep. Environments Final', label: 'Depositional Environments Final', weight: 2, maxScore: 20 },
          { id: 'pe_gis_fin', name: 'Cartography & GIS Final', label: 'Cartography and GIS Final', weight: 1, maxScore: 20 },
          { id: 'pe_gis_proj', name: 'Cartography & GIS Project', label: 'Cartography and GIS Project', weight: 1, maxScore: 20 },
          { id: 'pe_struct', name: 'Structural Geology', label: 'Structural Geology', weight: 2, maxScore: 20 },
          { id: 'pe_basin_fin', name: 'Basin Analysis Final', label: 'Basin Analysis & Stratigraphy Final', weight: 2, maxScore: 20 },
          { id: 'pe_ps_fin', name: 'Geology for PS Final', label: 'Geology for PS Final', weight: 2, maxScore: 20 },
          { id: 'pe_res_eng', name: 'Reservoir Engineering', label: 'Reservoir Engineering', weight: 2, maxScore: 20 },
          { id: 'pe_geochem_proj', name: 'Geochemistry(Project)', label: 'Geochemistry (Project)', weight: 1, maxScore: 20 },
          { id: 'pe_geochem_fin', name: 'Geochemistry Final', label: 'Geochemistry Final', weight: 1, maxScore: 20 },
        ],
      },
    ],
  },
  chem: {
    id: 'chem',
    name: 'Chemistry',
    frenchName: 'Chimie',
    partnerUniversity: 'Université de Strasbourg (Unistra)',
    level: 'L2',
    semester: 'Semester 4',
    totalEcts: 30,
    totalGpaWeight: 30,
    gpaFormulaText: 'GPA = (Vector Analysis × 5 + Chemistry_3 × 9 + French × 3 + Physics_3 × 5 + Physical and Molecular Chemistry 1 × 8) / 30',
    modules: [
      {
        id: 'chem_va',
        name: 'Vector Analysis',
        code: 'MATH-201',
        ects: 5,
        gpaWeight: 5,
        formulaDescription: 'Vector Analysis = (Notebook × 2 + Vector Analysis Midterm × 3 + Vector Analysis Final × 5) / 10',
        components: [
          { id: 'chem_va_nb', name: 'Notebook', label: 'Notebook', weight: 2, maxScore: 20 },
          { id: 'chem_va_mid', name: 'Midterm', label: 'Vector Analysis Midterm', weight: 3, maxScore: 20 },
          { id: 'chem_va_fin', name: 'Final', label: 'Vector Analysis Final', weight: 5, maxScore: 20 },
        ],
      },
      {
        id: 'chem_chem3',
        name: 'Chemistry_3',
        code: 'CHEM-203',
        ects: 9,
        gpaWeight: 9,
        formulaDescription: 'Chemistry_3 = ((Reactivity Midterm + Reactivity Final × 2)/3 × 3 + (Thermo and Kinetics Midterm + Thermo and Kinetics Final)/2 × 2 + Chem Evaluated PW × 3) / 8',
        subGroups: [
          {
            id: 'react',
            name: 'Reactivity (Coeff 3/8)',
            formulaText: '(Reactivity Midterm + Reactivity Final × 2) / 3',
            components: [
              { id: 'chem_chem3_react_mid', name: 'Midterm', label: 'Reactivity Midterm', maxScore: 20 },
              { id: 'chem_chem3_react_fin', name: 'Final', label: 'Reactivity Final', maxScore: 20 },
            ],
          },
          {
            id: 'thermo',
            name: 'Thermo and Kinetics (Coeff 2/8)',
            formulaText: '(Thermo and Kinetics Midterm + Thermo and Kinetics Final) / 2',
            components: [
              { id: 'chem_chem3_tk_mid', name: 'Midterm', label: 'Thermo & Kinetics Midterm', maxScore: 20 },
              { id: 'chem_chem3_tk_fin', name: 'Final', label: 'Thermo & Kinetics Final', maxScore: 20 },
            ],
          },
          {
            id: 'pw',
            name: 'Chemistry Evaluated PW (Coeff 3/8)',
            formulaText: 'Chem Evaluated PW Score',
            components: [
              { id: 'chem_chem3_eval_pw', name: 'PW', label: 'Chem Evaluated PW', maxScore: 20 },
            ],
          },
        ],
        components: [],
      },
      {
        id: 'chem_fr',
        name: 'French',
        code: 'LANG-201',
        ects: 3,
        gpaWeight: 3,
        formulaDescription: 'French = (French Midterm × 2 + French Speaking × 3 + French Final × 3) / 8',
        components: [
          { id: 'chem_fr_mid', name: 'French Midterm', label: 'French Midterm', weight: 2, maxScore: 20 },
          { id: 'chem_fr_spk', name: 'French Speaking', label: 'French Speaking', weight: 3, maxScore: 20 },
          { id: 'chem_fr_fin', name: 'French Final', label: 'French Final', weight: 3, maxScore: 20 },
        ],
      },
      {
        id: 'chem_phy3',
        name: 'Physics_3',
        code: 'PHYS-203',
        ects: 5,
        gpaWeight: 5,
        formulaDescription: 'Physics_3 = (Electricity + ((Thermodynamics Midterm + Thermodynamics Final) / 2)) / 2',
        components: [
          { id: 'chem_phy3_elec', name: 'Electricity', label: 'Electricity', weight: 1, maxScore: 20 },
          { id: 'chem_phy3_th_mid', name: 'Thermo Midterm', label: 'Thermodynamics Midterm', weight: 0.5, maxScore: 20 },
          { id: 'chem_phy3_th_fin', name: 'Thermo Final', label: 'Thermodynamics Final', weight: 0.5, maxScore: 20 },
        ],
      },
      {
        id: 'chem_pmc1',
        name: 'Physical and Molecular Chemistry 1',
        code: 'CHEM-205',
        ects: 8,
        gpaWeight: 8,
        formulaDescription: 'Physical and Molecular Chemistry 1 = ((SISDP PW Exam × 0.5 + SISDP TP noted × 0.3 + SISDP report × 0.2) × 0.4 + Molecular Dynamics/Cheminfo Exam × 0.3 + Molecular Chemistry 1 Exam × 0.3)',
        subGroups: [
          {
            id: 'sisdp',
            name: 'Scientific Instrumentation & Data Processing (40%)',
            formulaText: 'SISDP PW Exam × 0.5 + SISDP TP noted × 0.3 + SISDP report × 0.2',
            components: [
              { id: 'chem_pmc1_pw', name: 'PW Exam', label: 'SISDP PW Exam', maxScore: 20 },
              { id: 'chem_pmc1_tp', name: 'TP Noted', label: 'SISDP TP noted', maxScore: 20 },
              { id: 'chem_pmc1_rep', name: 'Report', label: 'SISDP report', maxScore: 20 },
            ],
          },
          {
            id: 'mol',
            name: 'Molecular Chemistry & Dynamics (60%)',
            formulaText: 'Molecular Dynamics Exam × 0.3 + Molecular Chemistry 1 Exam × 0.3',
            components: [
              { id: 'chem_pmc1_moldyn', name: 'Mol. Dynamics', label: 'Molecular Dynamics/Cheminfo Exam', maxScore: 20 },
              { id: 'chem_pmc1_molchem', name: 'Mol. Chem 1', label: 'Molecular Chemistry 1 Exam', maxScore: 20 },
            ],
          },
        ],
        components: [],
      },
    ],
  },
};
